import { useNavigate } from "react-router-dom";
import Controltable from "../../../components/controlled/Controltable";
import GenerateBillDialog from "./GenerateBill";
import { useState } from "react";
import { pathologyTests } from "./PathologyTestData";

export interface PathologyBill {
  id: number;
  billNo: string;
  visitId: string;
  date: string;
  patientName: string;
  generatedBy: string;
  doctor: string;
  amount: number;
  discount: string;
  tax: string;
  netAmount: number;
  paidAmount: number;
  refund: number;
  balanceAmount: number;
}

const Pathology = () => {
  const navigate = useNavigate();

  const [openDialog, setOpenDialog] = useState(false);
const [pathologyBills, setPathologyBills] = useState<PathologyBill[]>([]);

  const columns = [
    { key: "billNo", label: "Bill No" },
    { key: "visitId", label: "Visit ID" },
    { key: "date", label: "Date" },
    { key: "patientName", label: "Patient Name" },
    { key: "generatedBy", label: "Generated By" },
    { key: "doctor", label: "Doctor" },
    { key: "amount", label: "Amount" },
    { key: "discount", label: "Discount" },
    { key: "tax", label: "Tax" },
    { key: "netAmount", label: "Net Amount" },
    { key: "paidAmount", label: "Paid Amount" },
    { key: "refund", label: "Refund" },
    { key: "balanceAmount", label: "Balance Amount" },
  ];
  

  const handleSaveBill = (newBill: PathologyBill) => {
    setPathologyBills((prev) => [...prev, newBill]);
  };

  return (
    <div className="p-5">
      <div className="flex items-center justify-between mb-4">
        <div className="font-bold text-lg">
          Pathology Bill
        </div>

        <div className="flex gap-2">
          <button
            onClick={() => setOpenDialog(true)}
            className="bg-blue-500 text-white px-4 py-2 rounded-md font-bold"
          >
            + Generate Bill
          </button>

          <button
            onClick={() => navigate("/PathologyTest")}
            className="bg-green-500 text-white px-4 py-2 rounded-md font-bold"
          >
            Pathology Test
          </button>
        </div>
      </div>

      <Controltable
        columns={columns}
        data={pathologyBills}
        title=""
      />

      <GenerateBillDialog
        open={openDialog}
        onClose={() => setOpenDialog(false)}
        onSave={handleSaveBill}
        tests={pathologyTests}
      />
    </div>
  );
};

export default Pathology;
